app = "landmarking-ai"
primary_region = "jnb"  # Johannesburg (closest to Sierra Leone)
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  LOG_LEVEL = "INFO"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "5s"

[metrics]
  port = 8000
  path = "/metrics"

[deploy]
  strategy = "bluegreen"
  release_command = "python -c 'print(\"AI Service Started\")'"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"