name: Deploy AI Service

on:
  push:
    branches:
      - main
    paths:
      - 'src/ai/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Fly.io
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: src/ai/requirements.txt
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./src/ai
      
      - name: Run Linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        working-directory: ./src/ai
      
      - name: Run Tests
        run: |
          pip install pytest
          pytest
        working-directory: ./src/ai
      
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./src/ai
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: Notify Deployment
        if: success()
        run: |
          echo "AI Service successfully deployed to Fly.io"